<div class="wrapper">
    <h1>Framework runing</h1>
    <p>Start your project</p>
</div>
<section id="section">        
    <ul>
      <li><a href="#" class="instagram" id="instagram"><i class="fab fa-instagram"></i></a></li>
      <li><a href="#"class="github" id="github"><i class="fab fa-github"></i></a></li>
      <li><a href="#" class="linkedin" id="linkedin"><i class="fab fa-linkedin"></i></a></li>
    </ul>